server:
  port: 8085
spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my-demo?setUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 123456
  batch:
    jdbc:
      isolation-level-for-create: REPEATABLE_READ
      initialize-schema: always